### ISSUE TITLE
AllowedValues missing from process descriptions

### ISSUE THREAD

**Issue by davidcaron** [crim-ca/weaver#41]
The literal inputs' structure is not the same in the database as the one used in testbed14.

See: 
 - `weaver.wps_restapi.swagger_definitions.LiteralInputType`: testbed14
 - `weaver.wps_restapi.swagger_definitions.ProcessInputDescriptionSchema`: the one in the database (it's missing the allowedValues parameter, but adding it here will not add it in the process description)

So it basically comes down to 3 options I think:
 - Ignore the inputs description in the testbed14's format, and use ours instead
 - Convert our database schema to conform to testbed14's schema
 - Write a json function to support both schemas when sending the process description

I'm not sure how much work would be involved in any of these cases...

**Comment by fmigneault** [comment]
The `ProcessInputDescriptionSchema` is used for the `/providers/...` routes whereas the `/processes/...` conforms to the schemas established during TB14 with `ProcessOffering->...->LiteralInputType`.

Sadly, because of swagger 2.0, the oneOf don't display properly the `ProcessInputDescriptionSchema` with includes the `LiteralDataDomainTypeList` section nested under `InputType._one_of`, but only the `InputDataDescriptionType` fields.

Therefore, I would opt for the TB14 alternative with `literalDataDomains` definitions to remain consistent with the standard, and because it is the one already planed by the schema.

I can see that process `https://ogc-ems.crim.ca/weaver/processes/Finch_IceDays` has in the db the field `allowed_values` for input `freq`, which has all the necessary details (list of `{type:allowedvalue, value: <value>, etc.}`). These should be used to make the json output. I think the best place to do it is in json(), similarly how process_offering() adds extra fields on the fly.

https://github.com/crim-ca/weaver/blob/65f87dd49830e05ebbdb68b64267b4d82e19ead6/weaver/datatype.py#L700-L713
